name: plasticpaycoll
description: App for PlasticPay Collector

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  json_annotation: ^1.0.0
  http: ^0.12.0
  shared_preferences: ^0.5.1
  location: ^2.3.5
  path_provider: ^1.1.0
  qr_flutter: ^2.0.0+51
  barcode_scan: ^1.0.0
  intl: ^0.15.8
  url_launcher: ^5.1.0
  flare_flutter: ^1.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/